# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5feb791e9da92a22d82c97eb5b537e967c8c146fa5ed9090149924ededa4bd763b4081c0a1d16d01f3558dc47e1c72e8c6fe4850180bb86013bc42287afdc05e

test:
  secret_key_base: 7865af192072eaf82038e81e36f44acd5cecd1af773984a35283fac14e84e37876d3b20b0570a5fceac0a066baddb09017b60b5d1eddca29307b5a19f5b32d27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
